### PR TITLE
AGDIGGER-81 OSX sandbox definition file for CocoaPods

### PR DESCRIPTION
**Pull request by aliok**
See https://issues.jboss.org/browse/AGDIGGER-81

Comments in https://github.com/aerogear/digger-jenkins/pull/28 apply here too!

### CODE REVIEW

**Comment by aliok** [comment]
Verification:

```
cd /tmp
git clone https://github.com/feedhenry-templates/helloworld-ios.git
cd helloworld-ios
sandbox-exec -f /path/to/cocoapods_sandbox.sb pod install
```

If you want to try it again, make sure you delete everything that is fetched: `git clean -fdX`

**Comment by matzew** [comment]
how does this related to the sandbox-pod file, directly from CocoaPods

**Comment by aliok** [comment]
Has stuff in common. I developed the file checking there too.

**Comment by aliok** [comment]
@odra @wtrocki

**Comment by wtrocki** [comment]
Reviewed. Works good as example. More work would be carried later in integration phase.

**Pull request merged**
