### PR TITLE
update android keystore

### PR DESCRIPTION
**Pull request by laurafitzgerald**
@odra removing value for alias

### CODE REVIEW

**Comment by wei-lee** [comment]
@laurafitzgerald is this file required at all? All those values in this file are default settings, so I am thinking maybe this file isn't required?

**Comment by laurafitzgerald** [comment]
@wei-lee we use it [here](https://github.com/aerogear/digger-jenkins/blob/master/jenkinsfiles/cordova_jenkinsfile.groovy#L21) but i'm not sure what happens internally with the cordova command. @odra do you know?

**Comment by laurafitzgerald** [comment]
It's not required to run the command

**Comment by laurafitzgerald** [comment]
we could also pass the values like this `cordova build android --release -- --keystore="..\android.keystore" --storePassword=android --alias=mykey`

**Comment by laurafitzgerald** [comment]
@wei-lee I removed the build.json file and the app built successfully and certs were the same

**Comment by wei-lee** [comment]
@laurafitzgerald ok, in that case, let's remove the build.json file then

**Comment by laurafitzgerald** [comment]
@wei-lee file removed

**Pull request merged**
