### PR TITLE
Use openshift Centos base Dockerfile

### PR DESCRIPTION
**Pull request by PhilipGough**

### CODE REVIEW

**Comment by odra** [comment]
👍  Tested it locally

**Comment by wei-lee** [comment]
@PhilipGough @odra is this PR still valid?

**Comment by PhilipGough** [comment]
@wei-lee I think if @odra has made the fixes this was attempting to solve then its outdated at this point. Will wait for his confirmation on that

**Comment by odra** [comment]
Closing it due to #37

**Pull request closed without merging**
