### PR TITLE
AGDIGGER-70 - api user script

### PR DESCRIPTION
**Pull request by wtrocki**
## Motivation

Allow administrators to script user creation. We can add call to create users later based on this script.

Review @aliok @matzew

### CODE REVIEW

**Comment by aliok** [comment]
I am going to verify this later, but a quick suggestion: mind adding a `/admin` section in parent README.md?

**Comment by wtrocki** [comment]
Done!

**Comment by matzew** [comment]
👍

**Comment by aliok** [comment]
👍 
Verified on
* Our Jenkins image running on OpenShift: Jenkins ver. 2.19.3
* Our old Jenkins image running on OpenShift: Jenkins ver. 1.651.3

I first tried on another Jenkins instance running natively, but it failed there. Don't care why.

**Pull request merged**
